project:
    type: book
    output-dir: _book

book:
    title: "TRR 266: C02 ESEF Project"
    output-file: "esef-project"
    author: "Jeremiah Lewis & Collaborators"
    date: "2022-05-09"
    chapters:
        - index.qmd
        - data-collection.qmd
        - data-coverage.qmd
        - data-preview.qmd

format:
    html:
        theme: cosmo
        fig-format: retina
        code-fold: false
